name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Start fontend server
        run: nohup npm start &
      
      - name: Start backend server
        run: nohup npm run server &
      
      - name: Wait for servers to be ready
        run: |
          sleep 10
      
      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run tests
        run: npm test
  
  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-tests
    if: github.ref == 'refs/heads/master'
    
    steps:
      - name: Deploy Backend to Render 
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.BACKEND_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}
  
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-tests
    if: github.ref == 'refs/heads/master'
    
    steps:
      - name: Deploy Frontend to Render 
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.FRONTEND_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}

